# Generated by Django 6.0.6 on 2026-06-28 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_label', models.CharField(default='General Focus', max_length=100)),
                ('session_type', models.CharField(choices=[('WORK', 'Work Session'), ('SHORT_BREAK', 'Short Break'), ('LONG_BREAK', 'Long Break')], default='WORK', max_length=15)),
                ('duration_minutes', models.IntegerField(default=25)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_successfully', models.BooleanField(default=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracker.task')),
            ],
        ),
    ]
