# Generated by Django 6.0.6 on 2026-06-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='tree_type',
            field=models.CharField(default='OAK', max_length=20),
        ),
    ]
